# fly.toml app configuration file
app = 'koalens-backend'
primary_region = 'arn'

[build]
  builder = "heroku/builder:24"

# [deploy]
#  release_command = 'npm run build'

[env]
  NODE_ENV = 'production'
  PORT = '8080'

[processes]
  app = "node dist/server.js"

[[services]]
  processes = ["app"]
  protocol = "tcp"
  internal_port = 8080
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1